### ISSUE TITLE
[Todo] `<Header />` 개발 예정

### ISSUE THREAD

**Issue by Dorabang** [petD-ary/petDiary#32]
### 할 일
- `<Header />` 개발 예정

### 할 일 리스트
- [x] Header 컴포넌트 compound component pattern으로 제작 예정
- [x] 유형별 타입 header 제작
- [x] 겹치는 header css 조건부 설정

### 작업자
@juhee067
